### ISSUE TITLE
Doesn't support `colors` defined as a function

### ISSUE THREAD

**Issue by tommy-mitchell** [JavierM42/tailwind-mode-aware-colors#9]
Defining `theme.colors` as a function generates an empty `config.colors` value (`{}`):

```js
const config = {
  theme: {
    colors: ({ colors }) => ({
      black: colors.black,
      white: colors.white,
      primary: {
        light: '#bbffa3',
        dark: '#144b00'
      },
    }),
  },
};
```

A workaround is to [import the default colors](https://tailwindcss.com/docs/customizing-colors#using-the-default-colors) instead:

```js
const colors = require('tailwindcss/colors')

const config = {
  theme: {
    colors: {
      black: colors.black,
      white: colors.white,
      primary: {
        light: '#bbffa3',
        dark: '#144b00'
      },
    },
  },
};
```

**Comment by JavierM42** [comment]
I wasn't aware this way to define colors existed. Sadly, I don't think the plugin can work with a function. I'll update the README.
